version: 0.0.1
achievements:
  - achievement:
      name: Starring!!
      icon: https://raw.githubusercontent.com/simonmazzaroth/Vaunt_demo/main/.vaunt/_1bdeca15-e24d-4654-835f-2acdfaa893d1.png
      description: Awarded for starring our repository, make a wish!
      triggers:
        - trigger:
            actor: author
            action: star
            condition: starred = true
  - achievement:
      name: Snake Charmer 
      icon: https://raw.githubusercontent.com/elewis787/boa/develop/.vaunt/boa.png
      Description: Charming snakes is no easy feat! 
      triggers:
        - trigger:
            actor: author
            action: star
            condition: starred = true
            operator: "&"
        - trigger:
            actor: author
            action: issue
            condition: labels in ['enhancement']
            operator: "|"
        - trigger: 
            actor: reviewers
            action: pull_request
            condition: count() > 1
            operator: '|'
