version: 0.0.1
achievements:
  - achievement:
      name: Starring!!
      icon: https://raw.githubusercontent.com/simonmazzaroth/Example/main/.vaunt/1st%20place.png
      description: Awarded for starring our repository, make a wish!
      triggers:
        - trigger:
            actor: author
            action: star
            condition: starred = true
  - achievement:
      name: Snake Charmer 
      icon: https://raw.githubusercontent.com/elewis787/boa/develop/.vaunt/boa.png
      Description: Charming snakes is no easy feat! 
      triggers:
        - trigger:
            actor: author
            action: star
            condition: starred = true
            operator: "&"
        - trigger:
            actor: author
            action: issue
            condition: labels in ['enhancement']
            operator: "|"
        - trigger: 
            actor: reviewers
            action: pull_request
            condition: count() > 1
            operator: '|'
  - achievement:
      name: Docs Dash 1st Place
      icon: https://raw.githubusercontent.com/pingcap/docs/master/.vaunt/1st_place.png
      description: Awarded for starring our repository, make a wish!
      triggers:
        - trigger:
            actor: author
            action: star
            condition: starred = true
  - achievement:
      name: Docs Dash 2nd Place
      icon: https://raw.githubusercontent.com/pingcap/docs/master/.vaunt/2nd_place.png
      description: Awarded for starring our repository, make a wish!
      triggers:
        - trigger:
            actor: author
            action: star
            condition: starred = true  - achievement:
      name: Docs Dash 3th Place
      icon: https://raw.githubusercontent.com/pingcap/docs/master/.vaunt/3rd_place.png
      description: Awarded for starring our repository, make a wish!
      triggers:
        - trigger:
            actor: author
            action: star
            condition: starred = true
  - achievement:
      name: Docs Dash 4th Place
      icon: https://raw.githubusercontent.com/pingcap/docs/master/.vaunt/4th_place.png
      description: Awarded for starring our repository, make a wish!
      triggers:
        - trigger:
            actor: author
            action: star
            condition: starred = true  - achievement:
      name: Docs Dash 5th Place
      icon: https://raw.githubusercontent.com/pingcap/docs/master/.vaunt/5th_place.png
      description: Awarded for starring our repository, make a wish!
      triggers:
        - trigger:
            actor: author
            action: star
            condition: starred = true
  - achievement:
      name: Contributor
      icon: https://raw.githubusercontent.com/pingcap/docs/master/.vaunt/contributor.png
      description: Awarded for starring our repository, make a wish!
      triggers:
        - trigger:
            actor: author
            action: star
            condition: starred = true            
